name = "trading-logo-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "LOGO_CACHE"
id = "0bb94d70374f4eb594c954571637ff3e"

# Uncomment when ready to enable R2
# [[r2_buckets]]
# binding = "LOGO_IMAGES"
# bucket_name = "trading-logos"
